### ISSUE TITLE
error messages for known errors

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#70]
For MVP, we should do a first pass to cover the most common known errors and ensure they are classified as known errors with user-friendly error messages.

Let's start a checklist and we can add to it as we discover more:

- [x] `NoNodeVersionFoundError`
- [ ] `VersionParseError`
- [ ] `UnimplementedError`
- [ ] `DownloadFailedError`
- [ ] `AmbiguousVersionError`
- [ ] `DependenciesMissingError`
- [ ] ...?

**Comment by mikrostew** [comment]
I'll take some time to do a pass over the scenarios I can think of, and check error messages

**Comment by mikrostew** [comment]
We need some kind of error message for failed version parsing:

```
$ notion install pants
error: an internal error occurred
```

```
$ notion install 6.4.5.3
error: an internal error occurred
```

```
$ notion use what
error: an internal error occurred
```

```
$ notion default 6.4.3.2
error: an internal error occurred
```

**Comment by mikrostew** [comment]
And an error for things that are not implemented (instead of panicking):

```
$ notion config list
thread 'main' panicked at 'not yet implemented', src/command/config.rs:186:53
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
$ notion config set something blah
thread 'main' panicked at 'not yet implemented', src/command/config.rs:184:73
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
$ notion config edit
thread 'main' panicked at 'not yet implemented', src/command/config.rs:187:53
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
$ notion config delete something
thread 'main' panicked at 'not yet implemented', src/command/config.rs:185:66
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
$ npx cowsay "Moo"
thread 'main' panicked at 'not yet implemented', crates/notion-core/src/tool.rs:160:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
$ npm --version
thread 'main' panicked at 'not yet implemented', crates/notion-core/src/tool.rs:160:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by mikrostew** [comment]
In this case my WiFi was off and it failed to download the public node registry:

```
$ notion install 7
error: an internal error occurred
```

**Comment by mikrostew** [comment]
There should be some error for this case, because you can install using just the major version, but uninstall does not work the same way:

```
$ notion install 6

$ notion uninstall 6
error: an internal error occurred
```

**Comment by mikrostew** [comment]
If the project dependencies have not been installed this command fails:

```
$ notion shim something

$ notion shim
something
yarn
node
npx
npm

$ notion shim -v
error: an internal error occurred
```
